update workflow

diff --git a/.github/workflows/dst.yml b/.github/workflows/dst.yml
--- a/.github/workflows/dst.yml
+++ b/.github/workflows/dst.yml
@@ -115,4 +115,37 @@ jobs:
           path: logs-2.txt
 
       - name: Diff
-        run: diff logs-1.txt logs-2.txt || true
+        run: |
+          diff logs-1.txt logs-2.txt
+          exit 1
+
+      - name: Create issue if diff
+        if: ${{ failure() }}
+        uses: actions/github-script@v8
+        with:
+          script: |
+            github.rest.issues.create({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              title: `DST: ${{ needs.values.outputs.seed }}`,
+              labels: ['dst'],
+              body: `# DST Failed
+              Two DST runs produced different results for seed=${{ needs.values.outputs.seed }}, steps=${{ needs.values.outputs.steps }}, os=${{ matrix.os }}, version=${{ matrix.node-version }}.
+
+              **Seed**
+              ~~~
+              ${{ needs.values.outputs.seed }}
+              ~~~
+
+              **Commit**
+              ~~~
+              ${ process.env.GITHUB_SHA }
+              ~~~
+
+              **Command**
+              ~~~
+              npm run dst -- --seed ${{ needs.values.outputs.seed }} --steps ${{ needs.values.outputs.steps }}
+              ~~~
+
+              [more details](${ process.env.GITHUB_SERVER_URL }/${ process.env.GITHUB_REPOSITORY }/actions/runs/${ process.env.GITHUB_RUN_ID })`,
+            })
